#include"compiler.h"
#include"builtin_class.h"
#include"snake_class.h"
Begin
    #include"builtin_lib.h"
    #include"snake_lib.h"
    Output::Init();
    Math::Init();
    Array::Init();
    Snake::Main();
Finish
