class Snake{
    private:
    static void Title(){
        Call(Snake_Title);
        Output::Clean();
        }
    static void GameOver(){
        Call(GameOver,Global["score"]);
        Output::Clean();
        }
    static void Sleep(){
        Global["sleep"]=0;
        Global["sleepX"]=0x1000;
        Global["sleepY"]=Global["snack_length"];
        Global["sleepY"]-=5;
        Global["sleepY"]+=Global["sleepY"];
        Global["sleepY"]+=Global["sleepY"];
        Global["sleepY"]+=Global["sleepY"];
        Global["sleepY"]+=Global["sleepY"];
        Global["sleepY"]+=Global["sleepY"];
        Global["sleepY"]+=Global["sleepY"];
        Global["sleepX"]-=Global["sleepY"];
        Loop
            Input::Update();
            Global["sleep"]++;
            If(Global["sleep"],>=,Global["sleepX"])
                Break
            End
        End
        }
    public:
    static void Main(){
        Init();
        Snake::Title();
        Loop
            Global["score"]=0;
            Global["rand3"]=mem[KBD];
            Global["rand3"]-=130;
            Global["rand3"]+=Global["rand3"];
            Global["rand3"]+=Global["rand3"];
            Global["rand3"]+=Global["rand3"];
            Global["rand3"]+=Global["rand3"];
            Global["rand3"]+=Global["rand3"];
            Global["rand1"]+=Global["rand3"];
            Global["rand1"]+=7122;
            Global["rand2"]+=Global["rand3"];
            Global["rand2"]+=7777;
            Var vx,vy;
            Var mx,my;
            mx=16*7;
            my=16*7;
            const int ar=0x0400,snake_len=5;
            vx=16;
            vy=0;
            obj len=Global["snack_length"];
            len=snake_len;
            for(int i=0;i<snake_len;i++){
                mem[ar+i*2]=16*(snake_len-i-1);
                mem[ar+i*2+1]=0;
                }
            Loop
                Snake::Sleep();
                //Output::Clean();
                Input::Update();
                If(Input::Key(),==,130)
                    Var tmp;
                    tmp=mem[ar];
                    tmp-=mem[ar+2];
                    If(tmp,!=,16)
                        vx=-16;
                        vy=0;
                    End
                End
                If(Input::Key(),==,131)
                    Var tmp;
                    tmp=mem[ar+1];
                    tmp-=mem[ar+3];
                    If(tmp,!=,16)
                        vx=0;
                        vy=-16;
                    End
                End
                If(Input::Key(),==,132)
                    Var tmp;
                    tmp=mem[ar];
                    tmp-=mem[ar+2];
                    If(tmp,!=,-16)
                        vx=16;
                        vy=0;
                    End
                End
                If(Input::Key(),==,133)
                    Var tmp;
                    tmp=mem[ar+1];
                    tmp-=mem[ar+3];
                    If(tmp,!=,-16)
                        vx=0;
                        vy=16;
                    End
                End
                Input::Clean();
                Var i,j;
                i=ar;
                i+=len;
                i+=len;
                j=i;
                j--;
                Var x,xx,y,yy;
                y=mem[j];
                yy=y;
                yy+=15;
                j--;
                x=mem[j];
                xx=x;
                xx+=15;
                Output::DrawRect(x,xx,y,yy,0);
                Loop
                    i--;j--;
                    mem[i]=mem[j];
                    i--;j--;
                    mem[i]=mem[j];
                    If(i,==,ar+2)
                        Break
                    End
                End
                mem[ar]+=vx;
                mem[ar+1]+=vy;
                If(mem[ar],<,0)
                    Break
                End
                If(mem[ar+1],<,0)
                    Break
                End
                If(mem[ar],>=,512)
                    Break
                End
                If(mem[ar+1],>=,256)
                    Break
                End
                i=ar;
                i+=len;
                i+=len;
                Var gameover,snack_col;
                gameover=0;
                snack_col=len;
                snack_col++;
                snack_col&=1;
                Loop
                    Var x,y,xx,yy;
                    i--;
                    y=mem[i];
                    yy=y;
                    yy+=15;
                    i--;
                    x=mem[i];
                    xx=x;
                    xx+=15;
                    snack_col++;
                    Output::DrawRect(x,xx,y,yy,snack_col);
                    If(i,==,ar)
                        Break
                    End
                    If(mem[ar],==,x)
                        If(mem[ar+1],==,y)
                            gameover=1;
                            Break
                        End
                    End
                    snack_col&=1;
                End
                If(gameover,==,1)
                    Break
                End
                //Var x,y,xx,yy;
                y=my;
                yy=y;
                yy+=11;
                y+=4;
                x=mx;
                xx=x;
                xx+=11;
                x+=4;
                If(mx,==,mem[ar])
                    If(my,==,mem[ar+1])
                        len++;
                        Global["score"]++;
                        Loop
                            mx+=21525;
                            mx+=Global["rand1"];
                            my+=6732;
                            my+=Global["rand2"];
                            mx&=511^15;
                            my&=255^15;
                            Var ok;
                            ok=1;
                            i=ar;
                            i+=len;
                            i+=len;
                            j=i;
                            j--;
                            Var k;
                            Loop
                                i--;j--;
                                If(mem[i],==,my)
                                    If(mem[j],==,mx)
                                        ok=0;
                                        Break
                                    End
                                End
                                i--;j--;
                                If(i,==,ar+2)
                                    Break
                                End
                            End
                            If(ok,==,1)
                                Break
                            End
                        End
                    End
                End
                Output::DrawRect(x,xx,y,yy,2);
                x=mem[ar];
                xx=x;
                xx+=15;
                y=mem[ar+1];
                yy=y;
                yy+=15;
                Output::DrawRect(x,xx,y,yy,1);
                Output::Update();
            End
            Snake::GameOver();
        End
        }
    static void Init(){
        Call(Snake_Init);
        }
    };
